#!/bin/bash

# Aura Frog for Cursor IDE - Setup Script
# Version: 1.1.4
#
# This script installs Aura Frog to your project by copying
# the .cursor folder and setting up integrations.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CURSOR_SOURCE="$SCRIPT_DIR/.cursor"

# Banner
echo -e "${CYAN}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🐸 AURA FROG for Cursor IDE - Setup Script v1.1.4"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${NC}"

# Check if .cursor source exists
if [ ! -d "$CURSOR_SOURCE" ]; then
    echo -e "${RED}Error: .cursor folder not found at $CURSOR_SOURCE${NC}"
    echo "Please run this script from the aura-frog-cursor repository root."
    exit 1
fi

# Get target project path
if [ -n "$1" ]; then
    TARGET_PROJECT="$1"
else
    echo -e "${YELLOW}Enter the path to your target project:${NC}"
    read -r TARGET_PROJECT
fi

# Expand ~ to home directory
TARGET_PROJECT="${TARGET_PROJECT/#\~/$HOME}"

# Convert to absolute path
TARGET_PROJECT="$(cd "$TARGET_PROJECT" 2>/dev/null && pwd)" || {
    echo -e "${RED}Error: Invalid path '$TARGET_PROJECT'${NC}"
    exit 1
}

echo ""
echo -e "${BLUE}Target project:${NC} $TARGET_PROJECT"
echo ""

# Confirm installation
echo -e "${YELLOW}This will copy .cursor folder to your project.${NC}"
echo -e "${YELLOW}Existing files with the same name will be overwritten.${NC}"
echo ""
read -p "Continue? (y/N): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${RED}Setup cancelled.${NC}"
    exit 0
fi

# Copy .cursor folder
echo ""
echo -e "${BLUE}[1/4] Copying .cursor folder...${NC}"

if [ -d "$TARGET_PROJECT/.cursor" ]; then
    echo -e "${YELLOW}  Existing .cursor folder found. Merging files...${NC}"
fi

# Use rsync to copy and override existing files
rsync -av --progress "$CURSOR_SOURCE/" "$TARGET_PROJECT/.cursor/" > /dev/null 2>&1

echo -e "${GREEN}  ✓ .cursor folder installed${NC}"

# Setup .envrc
echo ""
echo -e "${BLUE}[2/4] Setting up environment file...${NC}"

ENVRC_TEMPLATE="$SCRIPT_DIR/.envrc.template"
ENVRC_TARGET="$TARGET_PROJECT/.envrc"

if [ -f "$ENVRC_TARGET" ]; then
    echo -e "${YELLOW}  .envrc already exists. Skipping template copy.${NC}"
    echo -e "${YELLOW}  You can manually update it or delete and re-run setup.${NC}"
elif [ -f "$ENVRC_TEMPLATE" ]; then
    cp "$ENVRC_TEMPLATE" "$ENVRC_TARGET"
    echo -e "${GREEN}  ✓ .envrc created from template${NC}"
else
    # Create default .envrc if template doesn't exist
    cat > "$ENVRC_TARGET" << 'ENVRC'
# Aura Frog - Environment Configuration
# Generated by setup.sh

# ============================================
# JIRA Integration
# ============================================
export JIRA_URL=""
export JIRA_EMAIL=""
export JIRA_API_TOKEN=""

# ============================================
# Figma Integration
# ============================================
export FIGMA_API_TOKEN=""

# ============================================
# Slack Integration (Optional)
# ============================================
export SLACK_WEBHOOK_URL=""

# ============================================
# Confluence Integration (Optional)
# ============================================
export CONFLUENCE_URL=""
export CONFLUENCE_EMAIL=""
export CONFLUENCE_API_TOKEN=""

# ============================================
# ElevenLabs Voice (Optional)
# ============================================
export ELEVENLABS_API_KEY=""
export ELEVENLABS_VOICE_ID="21m00Tcm4TlvDq8ikWAM"
ENVRC
    echo -e "${GREEN}  ✓ .envrc created with default template${NC}"
fi

# Configure JIRA
echo ""
echo -e "${BLUE}[3/4] Configuring JIRA integration...${NC}"
echo ""
echo -e "${CYAN}JIRA API Token can be created at:${NC}"
echo -e "  https://id.atlassian.com/manage-profile/security/api-tokens"
echo ""

read -p "Enter JIRA URL (e.g., https://company.atlassian.net) [skip]: " JIRA_URL_INPUT
if [ -n "$JIRA_URL_INPUT" ]; then
    read -p "Enter JIRA Email: " JIRA_EMAIL_INPUT
    read -p "Enter JIRA API Token: " -s JIRA_API_TOKEN_INPUT
    echo ""

    # Update .envrc with JIRA credentials (handle both commented and uncommented formats)
    # First try to uncomment and replace, then try to replace empty values
    sed -i.bak "s|# export JIRA_URL=.*|export JIRA_URL=\"$JIRA_URL_INPUT\"|" "$ENVRC_TARGET"
    sed -i.bak "s|# export JIRA_EMAIL=.*|export JIRA_EMAIL=\"$JIRA_EMAIL_INPUT\"|" "$ENVRC_TARGET"
    sed -i.bak "s|# export JIRA_API_TOKEN=.*|export JIRA_API_TOKEN=\"$JIRA_API_TOKEN_INPUT\"|" "$ENVRC_TARGET"
    # Also handle already uncommented empty values
    sed -i.bak "s|export JIRA_URL=\"\"|export JIRA_URL=\"$JIRA_URL_INPUT\"|" "$ENVRC_TARGET"
    sed -i.bak "s|export JIRA_EMAIL=\"\"|export JIRA_EMAIL=\"$JIRA_EMAIL_INPUT\"|" "$ENVRC_TARGET"
    sed -i.bak "s|export JIRA_API_TOKEN=\"\"|export JIRA_API_TOKEN=\"$JIRA_API_TOKEN_INPUT\"|" "$ENVRC_TARGET"
    rm -f "$ENVRC_TARGET.bak"

    echo -e "${GREEN}  ✓ JIRA configured${NC}"
else
    echo -e "${YELLOW}  ⊘ JIRA skipped${NC}"
fi

# Configure Figma
echo ""
echo -e "${BLUE}[4/4] Configuring Figma integration...${NC}"
echo ""
echo -e "${CYAN}Figma Access Token can be created at:${NC}"
echo -e "  https://www.figma.com/developers/api#access-tokens"
echo ""

read -p "Enter Figma Access Token [skip]: " -s FIGMA_TOKEN_INPUT
echo ""

if [ -n "$FIGMA_TOKEN_INPUT" ]; then
    # Update .envrc with Figma token (handle both commented and uncommented formats)
    sed -i.bak "s|# export FIGMA_API_TOKEN=.*|export FIGMA_API_TOKEN=\"$FIGMA_TOKEN_INPUT\"|" "$ENVRC_TARGET"
    sed -i.bak "s|export FIGMA_API_TOKEN=\"\"|export FIGMA_API_TOKEN=\"$FIGMA_TOKEN_INPUT\"|" "$ENVRC_TARGET"
    rm -f "$ENVRC_TARGET.bak"

    echo -e "${GREEN}  ✓ Figma configured${NC}"
else
    echo -e "${YELLOW}  ⊘ Figma skipped${NC}"
fi

# Add .envrc to .gitignore if not already there
GITIGNORE="$TARGET_PROJECT/.gitignore"
if [ -f "$GITIGNORE" ]; then
    if ! grep -q "^\.envrc$" "$GITIGNORE"; then
        echo "" >> "$GITIGNORE"
        echo "# Aura Frog environment (contains secrets)" >> "$GITIGNORE"
        echo ".envrc" >> "$GITIGNORE"
        echo -e "${GREEN}  ✓ Added .envrc to .gitignore${NC}"
    fi
else
    echo "# Aura Frog environment (contains secrets)" > "$GITIGNORE"
    echo ".envrc" >> "$GITIGNORE"
    echo -e "${GREEN}  ✓ Created .gitignore with .envrc${NC}"
fi

# Summary
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}${BOLD}  ✓ Aura Frog installed successfully!${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}Installed to:${NC} $TARGET_PROJECT/.cursor"
echo ""
echo -e "${BOLD}Files created:${NC}"
echo "  - .cursor/          (Aura Frog rules, commands, agents)"
echo "  - .envrc            (Environment configuration)"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Open your project in Cursor IDE"
echo "  2. Load environment: ${CYAN}source .envrc${NC}"
echo "  3. Initialize project: ${CYAN}/project:init${NC}"
echo "  4. Start workflow: ${CYAN}/workflow:start \"Your task\"${NC}"
echo ""
echo -e "${BOLD}Documentation:${NC}"
echo "  - Quick Start: ${CYAN}cat .cursor/GET_STARTED.md${NC}"
echo "  - Commands: ${CYAN}cat .cursor/commands/QUICK_REFERENCE.md${NC}"
echo ""
echo -e "${YELLOW}Note: Run 'source .envrc' to load environment variables.${NC}"
echo -e "${YELLOW}      Or use direnv for automatic loading.${NC}"
echo ""
echo -e "🐸 ${GREEN}Code with main character energy!${NC}"
echo ""
